name: Set up macOS Code Signing

inputs:
  MACOS_SIGNING_APPLICATION_IDENTITY:
    description: Application Identity for code signing
    required: true
  MACOS_SIGNING_CERT:
    description: Base64 encoded .p12 certificate
    required: true
  MACOS_SIGNING_CERT_PASSWORD:
    description: Password for the .p12 certificate
    required: true

outputs:
  CODESIGN_TEAM:
    description: The Team ID
    value: ${{ steps.extract.outputs.CODESIGN_TEAM }}

runs:
  using: "composite"
  steps:
    - name: Extract Codesign Identity
      id: extract
      shell: bash
      env:
        MACOS_SIGNING_APPLICATION_IDENTITY: ${{ inputs.MACOS_SIGNING_APPLICATION_IDENTITY }}
      run: |
        awk -F'[()]' '{ print "CODESIGN_TEAM=" $2 }' <<< "$MACOS_SIGNING_APPLICATION_IDENTITY" >> "$GITHUB_OUTPUT"

    - name: Import Signing Certificate
      shell: bash
      env:
        CERT_B64: ${{ inputs.MACOS_SIGNING_CERT }}
        CERT_PWD: ${{ inputs.MACOS_SIGNING_CERT_PASSWORD }}
        KEYCHAIN_PATH: ${{ runner.temp }}/app-signing.keychain-db
      run: |
        KEYCHAIN_PASSWORD=$(openssl rand -base64 32)

        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

        security default-keychain -s "$KEYCHAIN_PATH"

        base64 --decode <<< "$CERT_B64" > certificate.p12
        security import certificate.p12 -k "$KEYCHAIN_PATH" -P "$CERT_PWD" -T /usr/bin/codesign -T /usr/bin/productbuild
        rm certificate.p12

        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
