#!/bin/bash
IFS=$'\n'
include_files=(
  CMakeLists.txt
  $(find cmake -name "*.cmake")
  $(find src -name "CMakeLists.txt")
)
unset IFS

if [[ $# -eq 0 ]]; then
  set -- -i
fi

if [[ ${#include_files[@]} -gt 0 ]]; then
  gersemi "$@" "${include_files[@]}"
fi
